
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vszmwozumdybkwhdieme.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZzem13b3p1bWR5Ymt3aGRpZW1lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4MDIwNTMsImV4cCI6MjA1NzM3ODA1M30.-la_qBHrCQx4bH5SdliS23X12wAXoWKWAgP-EDgbjw8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create a client with automatic retries
export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true
    },
    // Add retry logic to handle connectivity issues
    global: {
      fetch: (url, options) => {
        return fetch(url, {
          ...options,
          // Reduce timeout to avoid hanging requests
          signal: AbortSignal.timeout(10000), // 10 second timeout
        });
      }
    }
  }
);
